services:
  - type: web
    name: rfp-evaluation-tool
    env: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free

